import { getJob,saveJob } from "@/lib/jobs";import { put } from "@vercel/blob";import { execFile } from "node:child_process";import { mkdtemp,readFile,rm,writeFile } from "node:fs/promises";import { tmpdir } from "node:os";import path from "node:path";import { promisify } from "node:util";import ffmpegPath from "ffmpeg-static";import type { Clip,Job } from "@/lib/types";
const exec=promisify(execFile);
async function update(id:string,stage:string,progress:number){"use step";const j=await getJob(id);if(!j)throw new Error("Job disappeared");j.status="processing";j.stage=stage;j.progress=progress;await saveJob(j)}
async function processVideo(job:Job){"use step";const dir=await mkdtemp(path.join(tmpdir(),"steamboy-"));try{if(!ffmpegPath)throw new Error("Packaged FFmpeg binary is unavailable.");const input=path.join(dir,"input");const response=await fetch(job.sourceUrl);if(!response.ok)throw new Error("Unable to download uploaded video.");await writeFile(input,Buffer.from(await response.arrayBuffer()));const script=path.join(process.cwd(),"python","analyze.py");const env={...process.env,FFMPEG_PATH:ffmpegPath};let stdout:string;try{({stdout}=await exec("python3",[script,input,dir,JSON.stringify(job.settings)],{env,maxBuffer:10*1024*1024,timeout:700_000}))}catch(e){throw new Error(`Analysis could not finish within the processing window. Shorten the video and try again. ${e instanceof Error?e.message:""}`)}
    const report=JSON.parse(stdout) as {duration:number;clips:Array<Omit<Clip,"url"> & {file:string;contactSheet:string}>};if(report.duration>180)throw new Error("Actual media duration exceeds the 3 minute limit.");const results:Clip[]=[];for(const c of report.clips){const video=await put(`outputs/${job.id}/${c.file}`,await readFile(path.join(dir,c.file)),{access:"public",contentType:"video/mp4"});let sheetUrl: string|undefined;if(c.contactSheet){const sheet=await put(`outputs/${job.id}/${c.contactSheet}`,await readFile(path.join(dir,c.contactSheet)),{access:"public",contentType:"image/jpeg"});sheetUrl=sheet.url}results.push({...c,url:video.url,contactSheetUrl:sheetUrl})}await put(`outputs/${job.id}/report.json`,JSON.stringify(report),{access:"public",contentType:"application/json"});return results}finally{await rm(dir,{recursive:true,force:true})}}
async function finish(id:string,results:Clip[]){"use step";const j=await getJob(id);if(!j)throw new Error("Job disappeared");j.status="complete";j.stage=`Selected ${results.length} highlights`;j.progress=100;j.results=results;await saveJob(j)}
async function fail(id:string,message:string){"use step";const j=await getJob(id);if(j){j.status="failed";j.stage="Analysis stopped";j.progress=100;j.error=message;await saveJob(j)}}
export async function analyzeVideo(id:string){"use workflow";try{const j=await getJob(id);if(!j)throw new Error("Job not found");await update(id,"Inspecting media and detecting scenes",15);const clips=await processVideo(j);await update(id,"Uploading clips and report",90);await finish(id,clips)}catch(e){await fail(id,e instanceof Error?e.message:"Unknown processing error")}}
export const maxDuration=800;
